### ISSUE TITLE
md-completed adds content: '7'; to the step label

### ISSUE THREAD

**Issue by coopernewby** [roelbarreto/md-steppers#23]
![image](https://cloud.githubusercontent.com/assets/5702661/18847262/58fb5750-83de-11e6-81ba-60529f600de4.png)
md-complete adds content: '7'; to the step label. Anyone else successful in fixing this small bug?

`<md-step label="Details" md-complete="c.completedStep2" ng-disabled="c.disabledStep2"></md-step>`

**Comment by coopernewby** [comment]
`.md-step.md-complete md-step-label-wrapper::before {
    content: '\7';
  .md-step.md-complete.md-active md-step-label-wrapper::before {
    content: '\7';`
Shouldnt it be     content: '\00A0'

**Comment by roelbarreto** [comment]
I will verify this and fix immediately
Thanks @coopernewby

**Comment by ghost** [comment]
Heyy I know it's been a long time since this has been opened, but the empty quotes for content is causing an issue where the text of the step label is misaligned, on FF and Chrome. If I change it to '\00A0' as @coopernewby suggests, the issue is fixed. Would you be receptive to a pull request with this change? Also, the demo page is out of date and reflects the old '\7' value for content (I have changed the value in the inspector in this screenshot to illustrate the alignment issue).
![screen shot 2019-01-24 at 12 47 43 pm](https://user-images.githubusercontent.com/17439898/51707515-473aa980-1fd6-11e9-94fa-ecf9fc8ed57c.png)

**Comment by roelbarreto** [comment]
Hi @hurricane987, If you can push the changes and make PR, I'll make a build for a hotfix on both bower and npm.
Regards...

**Comment by ghost** [comment]
Ok submitted the pull request. Thanks!
